language: python
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO_PACKAGE=Django==1.4.8
  - DJANGO_PACKAGE=Django==1.5.4
install:
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - python setup.py install
script: python runtests.py
