language: python
services:
  - mysql
  - postgresql
python:
  - "2.7"
  - "2.6"
env:
  - DJANGO_PACKAGE=Django==1.4.8
  - DJANGO_PACKAGE=Django==1.5.4
  - DJANGO_PACKAGE=Django==1.6
  - DB_BACKEND=sqlite
  - DB_BACKEND=mysql
  - DB_BACKEND=postgres
install:
  - pip install MySQL-python
  - pip install psycopg2
  - pip install -q $DJANGO_PACKAGE --use-mirrors
  - python setup.py install
before_script:
  - psql -c 'create database test_db;' -U postgres
  - mysql -e 'create database test_db;'
script: python runtests.py
